title: Weaviate Helm chart repo
description: Weaviate helm chart repo for storing charts.
theme: minima
url: "https://weaviate.github.io/weaviate-helm/"
repo_url: "https://github.com/weaviate/weaviate-helm"
repo_name: weaviate

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore