name: Main

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:

jobs:
  create-helm-chart:
    name: Test and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: ./.cicd/test.sh
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        run: .cicd/release.sh
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844  # pin 3rd-party actions by commit 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          draft: true
          files: weaviate/weaviate.tgz

  create-gh-page:
    name: create gh page
    runs-on: ubuntu-latest
    needs: create-helm-chart
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
